spring:
  profiles:
    active:
    - one
  application:
    name: springcloud-common #多个服务应用名相同
        
eureka:
  instance:
    instance-id: springcloud-common1 #向eureka中注册的实例名不同
    appname: ${spring.application.name}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
  client:
    service-url:
      #同时向eureka集群中的所有服务注册
      defaultZone: http://test1:9110/eureka/,http://test2:9120/eureka/